
package componentejb;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "garmentEJBBean", targetNamespace = "http://componentejb/")
@XmlSeeAlso({ ObjectFactory.class })
public interface GarmentEJBBean {


    /**
     *
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getConnection", targetNamespace = "http://componentejb/",
                    className = "componentejb.GetConnection")
    @ResponseWrapper(localName = "getConnectionResponse", targetNamespace = "http://componentejb/",
                     className = "componentejb.GetConnectionResponse")
    @Action(input = "http://componentejb/garmentEJBBean/getConnectionRequest",
            output = "http://componentejb/garmentEJBBean/getConnectionResponse")
    public int getConnection();

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "closeConexion", targetNamespace = "http://componentejb/",
                    className = "componentejb.CloseConexion")
    @ResponseWrapper(localName = "closeConexionResponse", targetNamespace = "http://componentejb/",
                     className = "componentejb.CloseConexionResponse")
    @Action(input = "http://componentejb/garmentEJBBean/closeConexionRequest",
            output = "http://componentejb/garmentEJBBean/closeConexionResponse")
    public boolean closeConexion(@WebParam(name = "arg0", targetNamespace = "") int arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertGarment", targetNamespace = "http://componentejb/",
                    className = "componentejb.InsertGarment")
    @ResponseWrapper(localName = "insertGarmentResponse", targetNamespace = "http://componentejb/",
                     className = "componentejb.InsertGarmentResponse")
    @Action(input = "http://componentejb/garmentEJBBean/insertGarmentRequest",
            output = "http://componentejb/garmentEJBBean/insertGarmentResponse")
    public boolean insertGarment(@WebParam(name = "arg0", targetNamespace = "") Garment arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateGarment", targetNamespace = "http://componentejb/",
                    className = "componentejb.UpdateGarment")
    @ResponseWrapper(localName = "updateGarmentResponse", targetNamespace = "http://componentejb/",
                     className = "componentejb.UpdateGarmentResponse")
    @Action(input = "http://componentejb/garmentEJBBean/updateGarmentRequest",
            output = "http://componentejb/garmentEJBBean/updateGarmentResponse")
    public boolean updateGarment(@WebParam(name = "arg0", targetNamespace = "") Garment arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeGarment", targetNamespace = "http://componentejb/",
                    className = "componentejb.RemoveGarment")
    @ResponseWrapper(localName = "removeGarmentResponse", targetNamespace = "http://componentejb/",
                     className = "componentejb.RemoveGarmentResponse")
    @Action(input = "http://componentejb/garmentEJBBean/removeGarmentRequest",
            output = "http://componentejb/garmentEJBBean/removeGarmentResponse")
    public boolean removeGarment(@WebParam(name = "arg0", targetNamespace = "") Garment arg0);

    /**
     *
     * @return
     *     returns java.util.List<componentejb.Garment>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGarments", targetNamespace = "http://componentejb/",
                    className = "componentejb.GetGarments")
    @ResponseWrapper(localName = "getGarmentsResponse", targetNamespace = "http://componentejb/",
                     className = "componentejb.GetGarmentsResponse")
    @Action(input = "http://componentejb/garmentEJBBean/getGarmentsRequest",
            output = "http://componentejb/garmentEJBBean/getGarmentsResponse")
    public List<Garment> getGarments();

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "commit", targetNamespace = "http://componentejb/", className = "componentejb.Commit")
    @ResponseWrapper(localName = "commitResponse", targetNamespace = "http://componentejb/",
                     className = "componentejb.CommitResponse")
    @Action(input = "http://componentejb/garmentEJBBean/commitRequest",
            output = "http://componentejb/garmentEJBBean/commitResponse")
    public boolean commit(@WebParam(name = "arg0", targetNamespace = "") int arg0);

}
