package prendapps;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1224
public class RequestEJBBeanPortClient {
    public static void main(String[] args) {
        RequestEJBBeanService requestEJBBeanService = new RequestEJBBeanService();
        RequestEJBBean requestEJBBean = requestEJBBeanService.getRequestEJBBeanPort();
        
        
        int conn = requestEJBBean.getConnection();
        System.out.println(conn);
        
        if(conn >= 0) requestEJBBean.closeConection(conn);


    }
}
