package prendapps;

import controllers.ProgramState;
import controllers.Request_Controller;
import model.ForTable;
import views.Request_View;
import java.util.ArrayList;
import java.util.List;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1224
public class RequestEJBBeanPortClient {
    
    static int conn = -1;
    public static void main(String[] args) {
        RequestEJBBeanService requestEJBBeanService = new RequestEJBBeanService();
        RequestEJBBean requestEJBBean = requestEJBBeanService.getRequestEJBBeanPort();
    
        conn = requestEJBBean.getConnection();
        
        ProgramState.getInstance().setBean(requestEJBBean);
        ProgramState.getInstance().setConn(conn);
        
        ArrayList<LineRequest> lr = (ArrayList<LineRequest>) requestEJBBean.getLRfromRequest(1);
        //for(LinewRe)
        
                System.out.println(conn);
                
                List<Request> list = requestEJBBean.getRequests();
                
                ArrayList<ForTable> newModel = new ArrayList<ForTable>();
                for (Request rq : list) newModel.add(rq);
                
                if(conn >= 0) {
                    Request_View view;
                    Request_Controller controller;
                    
                    view = new Request_View();
                    controller = new Request_Controller(view, newModel, requestEJBBean);
                }
                //requestEJBBean.closeConection(conn);
    }
}
