
package prendapps;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "RequestEJBBean", targetNamespace = "http://prendapps/")
@XmlSeeAlso({ ObjectFactory.class })
public interface RequestEJBBean {


    /**
     *
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getConnection", targetNamespace = "http://prendapps/",
                    className = "prendapps.GetConnection")
    @ResponseWrapper(localName = "getConnectionResponse", targetNamespace = "http://prendapps/",
                     className = "prendapps.GetConnectionResponse")
    @Action(input = "http://prendapps/RequestEJBBean/getConnectionRequest",
            output = "http://prendapps/RequestEJBBean/getConnectionResponse")
    public int getConnection();

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "commit", targetNamespace = "http://prendapps/", className = "prendapps.Commit")
    @ResponseWrapper(localName = "commitResponse", targetNamespace = "http://prendapps/",
                     className = "prendapps.CommitResponse")
    @Action(input = "http://prendapps/RequestEJBBean/commitRequest",
            output = "http://prendapps/RequestEJBBean/commitResponse")
    public boolean commit(@WebParam(name = "arg0", targetNamespace = "") int arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeLineRequest", targetNamespace = "http://prendapps/",
                    className = "prendapps.RemoveLineRequest")
    @ResponseWrapper(localName = "removeLineRequestResponse", targetNamespace = "http://prendapps/",
                     className = "prendapps.RemoveLineRequestResponse")
    @Action(input = "http://prendapps/RequestEJBBean/removeLineRequestRequest",
            output = "http://prendapps/RequestEJBBean/removeLineRequestResponse")
    public boolean removeLineRequest(@WebParam(name = "arg0", targetNamespace = "") LineRequest arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateLineRequest", targetNamespace = "http://prendapps/",
                    className = "prendapps.UpdateLineRequest")
    @ResponseWrapper(localName = "updateLineRequestResponse", targetNamespace = "http://prendapps/",
                     className = "prendapps.UpdateLineRequestResponse")
    @Action(input = "http://prendapps/RequestEJBBean/updateLineRequestRequest",
            output = "http://prendapps/RequestEJBBean/updateLineRequestResponse")
    public boolean updateLineRequest(@WebParam(name = "arg0", targetNamespace = "") LineRequest arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertLineRequest", targetNamespace = "http://prendapps/",
                    className = "prendapps.InsertLineRequest")
    @ResponseWrapper(localName = "insertLineRequestResponse", targetNamespace = "http://prendapps/",
                     className = "prendapps.InsertLineRequestResponse")
    @Action(input = "http://prendapps/RequestEJBBean/insertLineRequestRequest",
            output = "http://prendapps/RequestEJBBean/insertLineRequestResponse")
    public boolean insertLineRequest(@WebParam(name = "arg0", targetNamespace = "") LineRequest arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateRequest", targetNamespace = "http://prendapps/",
                    className = "prendapps.UpdateRequest")
    @ResponseWrapper(localName = "updateRequestResponse", targetNamespace = "http://prendapps/",
                     className = "prendapps.UpdateRequestResponse")
    @Action(input = "http://prendapps/RequestEJBBean/updateRequestRequest",
            output = "http://prendapps/RequestEJBBean/updateRequestResponse")
    public boolean updateRequest(@WebParam(name = "arg0", targetNamespace = "") Request arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeRequest", targetNamespace = "http://prendapps/",
                    className = "prendapps.RemoveRequest")
    @ResponseWrapper(localName = "removeRequestResponse", targetNamespace = "http://prendapps/",
                     className = "prendapps.RemoveRequestResponse")
    @Action(input = "http://prendapps/RequestEJBBean/removeRequestRequest",
            output = "http://prendapps/RequestEJBBean/removeRequestResponse")
    public boolean removeRequest(@WebParam(name = "arg0", targetNamespace = "") Request arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertRequest", targetNamespace = "http://prendapps/",
                    className = "prendapps.InsertRequest")
    @ResponseWrapper(localName = "insertRequestResponse", targetNamespace = "http://prendapps/",
                     className = "prendapps.InsertRequestResponse")
    @Action(input = "http://prendapps/RequestEJBBean/insertRequestRequest",
            output = "http://prendapps/RequestEJBBean/insertRequestResponse")
    public boolean insertRequest(@WebParam(name = "arg0", targetNamespace = "") Request arg0);

    /**
     *
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hola", targetNamespace = "http://prendapps/", className = "prendapps.Hola")
    @ResponseWrapper(localName = "holaResponse", targetNamespace = "http://prendapps/",
                     className = "prendapps.HolaResponse")
    @Action(input = "http://prendapps/RequestEJBBean/holaRequest",
            output = "http://prendapps/RequestEJBBean/holaResponse")
    public String hola();

    /**
     *
     * @return
     *     returns java.util.List<prendapps.LineRequest>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLineRquests", targetNamespace = "http://prendapps/",
                    className = "prendapps.GetLineRquests")
    @ResponseWrapper(localName = "getLineRquestsResponse", targetNamespace = "http://prendapps/",
                     className = "prendapps.GetLineRquestsResponse")
    @Action(input = "http://prendapps/RequestEJBBean/getLineRquestsRequest",
            output = "http://prendapps/RequestEJBBean/getLineRquestsResponse")
    public List<LineRequest> getLineRquests();

    /**
     *
     * @param arg0
     * @return
     *     returns java.util.List<prendapps.LineRequest>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLRfromRequest", targetNamespace = "http://prendapps/",
                    className = "prendapps.GetLRfromRequest")
    @ResponseWrapper(localName = "getLRfromRequestResponse", targetNamespace = "http://prendapps/",
                     className = "prendapps.GetLRfromRequestResponse")
    @Action(input = "http://prendapps/RequestEJBBean/getLRfromRequestRequest",
            output = "http://prendapps/RequestEJBBean/getLRfromRequestResponse")
    public List<LineRequest> getLRfromRequest(@WebParam(name = "arg0", targetNamespace = "") int arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "closeConection", targetNamespace = "http://prendapps/",
                    className = "prendapps.CloseConection")
    @ResponseWrapper(localName = "closeConectionResponse", targetNamespace = "http://prendapps/",
                     className = "prendapps.CloseConectionResponse")
    @Action(input = "http://prendapps/RequestEJBBean/closeConectionRequest",
            output = "http://prendapps/RequestEJBBean/closeConectionResponse")
    public boolean closeConection(@WebParam(name = "arg0", targetNamespace = "") int arg0);

    /**
     *
     * @return
     *     returns java.util.List<prendapps.Request>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRequests", targetNamespace = "http://prendapps/",
                    className = "prendapps.GetRequests")
    @ResponseWrapper(localName = "getRequestsResponse", targetNamespace = "http://prendapps/",
                     className = "prendapps.GetRequestsResponse")
    @Action(input = "http://prendapps/RequestEJBBean/getRequestsRequest",
            output = "http://prendapps/RequestEJBBean/getRequestsResponse")
    public List<Request> getRequests();

}
