package prendapps;

import controllers.ProgramState;
import controllers.Request_Controller;

import model.ForTable;

import views.Request_View;

import java.util.ArrayList;
import java.util.List;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1224
public class RequestEJBBeanPortClient {

    static int conn = -1;

    public static void main(String[] args) {
        RequestEJBBeanService requestEJBBeanService = new RequestEJBBeanService();
        RequestEJBBean requestEJBBean = requestEJBBeanService.getRequestEJBBeanPort();
        // Add your code to call the desired methods.


    }
}
