SET SQLBLANKLINES ON
CREATE TABLE CLIENT 
(
  ID INT GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 0 MAXVALUE 1000000 MINVALUE 0 NOT NULL 
, COUNTRY VARCHAR2(20) NOT NULL 
, ID_NUMBER NUMBER(9) NOT NULL 
, NAME VARCHAR2(20) NOT NULL 
, LASTNAME VARCHAR2(20) NOT NULL 
, DIRECTION VARCHAR2(30) NOT NULL 
, EMAIL VARCHAR2(20) NOT NULL 
, PHONE NUMBER(8) NOT NULL 
, PAYMENT_DIRECTION VARCHAR2(40) NOT NULL 
, CONSTRAINT CLIENT_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
PCTFREE 30 
PCTUSED 55 
INITRANS 1 
STORAGE 
( 
  INITIAL 455000 
  NEXT 5000 
  MINEXTENTS 1 
  PCTINCREASE 0 
  FREELISTS 2 
  FREELIST GROUPS 2 
);

CREATE TABLE GARMENT 
(
  ID INT GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 0 MAXVALUE 100000 MINVALUE 0 NOT NULL 
, DESCRIPTION VARCHAR2(120) NOT NULL 
, UNIT_COST DOUBLE PRECISION NOT NULL 
, IMAGE BLOB NOT NULL 
, VIDEO BLOB NOT NULL 
, CONSTRAINT GARMENT_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
PCTFREE 30 
PCTUSED 60 
INITRANS 1 
STORAGE 
( 
  INITIAL 176000 
  NEXT 176000 
  MINEXTENTS 1 
  PCTINCREASE 0 
  FREELISTS 2 
  FREELIST GROUPS 2 
);

CREATE TABLE PROVIDER 
(
  ID INT GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 0 MAXVALUE 1000000 MINVALUE 0 NOT NULL 
, TYPE CHAR(1) NOT NULL 
, NAME VARCHAR2(30) NOT NULL 
, DIRECTION VARCHAR2(30) NOT NULL 
, EMAIL VARCHAR2(20) NOT NULL 
, PHONE NUMBER(8) NOT NULL 
, CONTACT_NAME VARCHAR2(30) NOT NULL 
, CONSTRAINT PROVIDER_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
PCTFREE 30 
PCTUSED 65 
INITRANS 1 
STORAGE 
( 
  INITIAL 13107200 
  NEXT 2560000 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  FREELISTS 1 
  FREELIST GROUPS 2 
);

CREATE TABLE RAW_MATERIAL 
(
  ID INT GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 0 MAXVALUE 10000000 MINVALUE 0 NOT NULL 
, UNIT VARCHAR2(4) NOT NULL 
, MIN_QUANTITY DOUBLE PRECISION NOT NULL 
, CURRENT_EXISTENCE DOUBLE PRECISION NOT NULL 
, UNIT_COST DOUBLE PRECISION NOT NULL 
, DESCRIPTION VARCHAR2(50) NOT NULL 
, CONSTRAINT RAW_MATERIAL_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
PCTFREE 10 
PCTUSED 75 
INITRANS 1 
STORAGE 
( 
  INITIAL 1100000 
  NEXT 100000 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 10 
  FREELISTS 3 
  FREELIST GROUPS 3 
);

CREATE TABLE STYLE 
(
  ID INT GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 0 MAXVALUE 1000000 MINVALUE 0 NOT NULL 
, COLOR VARCHAR2(10) NOT NULL 
, DESCRIPTION VARCHAR2(50) NOT NULL 
, CONSTRAINT STYLE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
PCTFREE 20 
PCTUSED 70 
INITRANS 1 
STORAGE 
( 
  INITIAL 450000 
  NEXT 450000 
  MINEXTENTS 1 
  PCTINCREASE 0 
  FREELISTS 2 
  FREELIST GROUPS 2 
);

CREATE TABLE REQUEST 
(
  ID INT GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 0 MAXVALUE 1000000 MINVALUE 0 NOT NULL 
, CLIENT INT NOT NULL 
, REQUEST_DATE DATE NOT NULL 
, DELIVER_DATE DATE NOT NULL 
, CONSTRAINT REQUEST_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
PCTFREE 20 
PCTUSED 65 
INITRANS 1 
STORAGE 
( 
  INITIAL 1320000 
  NEXT 1320000 
  MINEXTENTS 1 
  PCTINCREASE 0 
  FREELISTS 2 
  FREELIST GROUPS 2 
);

CREATE TABLE FOREIGN_PROVIDER 
(
  PROVIDER INT NOT NULL 
, BANK VARCHAR2(30) NOT NULL 
, ACCOUNT NUMBER(16) NOT NULL 
, CONSTRAINT FOREIGN_PROVIDER_PK PRIMARY KEY 
  (
    PROVIDER 
  )
  ENABLE 
);

CREATE TABLE NATIONAL_PROVIDER 
(
  ID INT NOT NULL 
, IDENTIFICATION_NUMBER NUMBER(11) NOT NULL 
, MAX_DAYS INT NOT NULL 
, CONSTRAINT NATIONAL_PROVIDER_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE PURCHASE_ORDER 
(
  ID INT GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 0 MAXVALUE 1000000 MINVALUE 0 NOT NULL 
, ORDER_DATE DATE NOT NULL 
, PROVIDER INT NOT NULL 
, WAITING CHAR(1) NOT NULL 
, CONSTRAINT PURCHASE_ORDER_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
PCTFREE 5 
PCTUSED 90 
INITRANS 1 
STORAGE 
( 
  INITIAL 3200 
  NEXT 3200 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  FREELISTS 3 
  FREELIST GROUPS 3 
);

CREATE TABLE RAWMATERIAL_PROVIDER 
(
  RAW_MATERIAL INT NOT NULL 
, PROVIDER INT NOT NULL 
, UNIT_COST DOUBLE PRECISION NOT NULL 
, MIN_QUANTITY DOUBLE PRECISION NOT NULL 
, DELIVER_TIME INT NOT NULL 
, CONSTRAINT RAWMATERIAL_PROVIDER_PK PRIMARY KEY 
  (
    PROVIDER 
  , RAW_MATERIAL 
  )
  ENABLE 
) 
PCTFREE 5 
PCTUSED 90 
INITRANS 1 
STORAGE 
( 
  INITIAL 960000 
  NEXT 960000 
  MINEXTENTS 1 
  PCTINCREASE 0 
  FREELISTS 2 
  FREELIST GROUPS 2 
);

CREATE TABLE RECIPE 
(
  ID INT GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 0 MAXVALUE 10000000 MINVALUE 0 NOT NULL 
, GARMENT INT NOT NULL 
, STYLE INT NOT NULL 
, GARMENT_SIZE VARCHAR2(3) NOT NULL 
, CONSTRAINT RECIPE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
PCTFREE 10 
PCTUSED 85 
INITRANS 1 
STORAGE 
( 
  INITIAL 600000 
  NEXT 600000 
  MINEXTENTS 1 
  PCTINCREASE 0 
  FREELISTS 2 
  FREELIST GROUPS 2 
);

CREATE TABLE LINE_PURCHASE_ORDER 
(
  PURCHASE_ORDER INT NOT NULL 
, RAW_MATERIAL INT NOT NULL 
, QUANTITY DOUBLE PRECISION 
, CONSTRAINT LINE_PURCHASE_ORDER_PK PRIMARY KEY 
  (
    PURCHASE_ORDER 
  , RAW_MATERIAL 
  )
  ENABLE 
) 
PCTFREE 5 
PCTUSED 90 
INITRANS 1 
STORAGE 
( 
  INITIAL 9600 
  NEXT 1920 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  FREELISTS 3 
  FREELIST GROUPS 3 
);

CREATE TABLE LINE_REQUEST 
(
  ID INT NOT NULL 
, LINE_ID INT NOT NULL 
, RECEIPE INT NOT NULL 
, QUANTITY DOUBLE PRECISION NOT NULL 
, PROGRAMMED_DATE DATE NOT NULL 
, CONSTRAINT LINE_REQUEST_PK PRIMARY KEY 
  (
    ID 
  , LINE_ID 
  , RECEIPE 
  )
  ENABLE 
) 
PCTFREE 10 
PCTUSED 80 
INITRANS 1 
STORAGE 
( 
  INITIAL 32400000 
  NEXT 32400000 
  MINEXTENTS 1 
  PCTINCREASE 0 
  FREELISTS 5 
  FREELIST GROUPS 5 
);

CREATE TABLE RECIPE_RAWMATERIAL 
(
  RECIPE INT NOT NULL 
, RAW_MATERIAL INT NOT NULL 
, QUANTITY DOUBLE PRECISION NOT NULL 
, CONSTRAINT RECIPE_RAWMATERIAL_PK PRIMARY KEY 
  (
    RECIPE 
  , RAW_MATERIAL 
  )
  ENABLE 
) 
PCTFREE 5 
PCTUSED 85 
INITRANS 1 
STORAGE 
( 
  INITIAL 6400000 
  NEXT 100000 
  MINEXTENTS 1 
  PCTINCREASE 0 
  FREELISTS 2 
  FREELIST GROUPS 2 
);

ALTER TABLE NATIONAL_PROVIDER
ADD CONSTRAINT NATIONAL_PROVIDER_UK UNIQUE 
(
  IDENTIFICATION_NUMBER 
)
ENABLE;

ALTER TABLE FOREIGN_PROVIDER
ADD CONSTRAINT FOREIGN_PROVIDER_PROVIDER_FK FOREIGN KEY
(
  PROVIDER 
)
REFERENCES PROVIDER
(
  ID 
)
ENABLE;

ALTER TABLE LINE_PURCHASE_ORDER
ADD CONSTRAINT HEADER_LINE_PURCHASE_ORDER_FK FOREIGN KEY
(
  PURCHASE_ORDER 
)
REFERENCES PURCHASE_ORDER
(
  ID 
)
ENABLE;

ALTER TABLE LINE_PURCHASE_ORDER
ADD CONSTRAINT LINE_PURCHASE_ORDER_RM_FK FOREIGN KEY
(
  RAW_MATERIAL 
)
REFERENCES RAW_MATERIAL
(
  ID 
)
ENABLE;

ALTER TABLE LINE_REQUEST
ADD CONSTRAINT LINE_REQUEST_RECIPE_FK FOREIGN KEY
(
  RECEIPE 
)
REFERENCES RECIPE
(
  ID 
)
ENABLE;

ALTER TABLE LINE_REQUEST
ADD CONSTRAINT LINE_REQUEST_REQUEST_FK FOREIGN KEY
(
  ID 
)
REFERENCES REQUEST
(
  ID 
)
ENABLE;

ALTER TABLE NATIONAL_PROVIDER
ADD CONSTRAINT NATIONAL_PROVIDER_FK FOREIGN KEY
(
  ID 
)
REFERENCES PROVIDER
(
  ID 
)
ENABLE;

ALTER TABLE PURCHASE_ORDER
ADD CONSTRAINT PURCHASE_ORDER_PROVIDER_FK FOREIGN KEY
(
  PROVIDER 
)
REFERENCES PROVIDER
(
  ID 
)
ENABLE;

ALTER TABLE RAWMATERIAL_PROVIDER
ADD CONSTRAINT RAWMATERIAL_PROVIDER_FK1 FOREIGN KEY
(
  PROVIDER 
)
REFERENCES PROVIDER
(
  ID 
)
ENABLE;

ALTER TABLE RAWMATERIAL_PROVIDER
ADD CONSTRAINT RAWMATERIAL_PROVIDER_FK2 FOREIGN KEY
(
  RAW_MATERIAL 
)
REFERENCES RAW_MATERIAL
(
  ID 
)
ENABLE;

ALTER TABLE RECIPE
ADD CONSTRAINT RECIPE_GARMENT_FK FOREIGN KEY
(
  GARMENT 
)
REFERENCES GARMENT
(
  ID 
)
ENABLE;

ALTER TABLE RECIPE
ADD CONSTRAINT RECIPE_STYLE_FK FOREIGN KEY
(
  STYLE 
)
REFERENCES STYLE
(
  ID 
)
ENABLE;

ALTER TABLE RECIPE_RAWMATERIAL
ADD CONSTRAINT RECIPE_RAWMATERIAL_FK FOREIGN KEY
(
  RAW_MATERIAL 
)
REFERENCES RAW_MATERIAL
(
  ID 
)
ENABLE;

ALTER TABLE RECIPE_RAWMATERIAL
ADD CONSTRAINT RECIPE_RAWMATERIAL_RECIPE_FK FOREIGN KEY
(
  RECIPE 
)
REFERENCES RECIPE
(
  ID 
)
ENABLE;

ALTER TABLE REQUEST
ADD CONSTRAINT REQUEST_CLIENT_FK FOREIGN KEY
(
  CLIENT 
)
REFERENCES CLIENT
(
  ID 
)
ENABLE;

ALTER TABLE RECIPE
ADD CONSTRAINT GARMENT_SIZE_CK CHECK 
(GARMENT_SIZE = 'S' OR GARMENT_SIZE = 'M' OR GARMENT_SIZE = 'L' OR GARMENT_SIZE = 'XXL')
ENABLE;

COMMENT ON TABLE GARMENT IS 'Tabla para representar las prendas';

COMMENT ON COLUMN FOREIGN_PROVIDER.BANK IS 'Banco para depositar';

COMMENT ON COLUMN FOREIGN_PROVIDER.ACCOUNT IS 'Cuenta bancaria';

COMMENT ON COLUMN GARMENT.DESCRIPTION IS 'Descripcion de la prenda';

COMMENT ON COLUMN GARMENT.UNIT_COST IS 'Costo por unidad';

COMMENT ON COLUMN GARMENT.IMAGE IS 'Imagen';

COMMENT ON COLUMN GARMENT.VIDEO IS 'Video de la prenda';

COMMENT ON COLUMN NATIONAL_PROVIDER.IDENTIFICATION_NUMBER IS 'Cedula';

COMMENT ON COLUMN NATIONAL_PROVIDER.MAX_DAYS IS 'Pais';

COMMENT ON COLUMN PROVIDER.TYPE IS 'Extranjero o nacional';

COMMENT ON COLUMN PROVIDER.NAME IS 'Nombre';

COMMENT ON COLUMN PROVIDER.DIRECTION IS 'Direccion';

COMMENT ON COLUMN PROVIDER.EMAIL IS 'Correo electronico';

COMMENT ON COLUMN PROVIDER.PHONE IS 'Telefono';

COMMENT ON COLUMN PROVIDER.CONTACT_NAME IS 'Nombre del contacto';

COMMENT ON COLUMN PURCHASE_ORDER.ORDER_DATE IS 'Fecha en que se emite la orden';

COMMENT ON COLUMN PURCHASE_ORDER.PROVIDER IS 'Proveedor a quien se le compra';

COMMENT ON COLUMN PURCHASE_ORDER.WAITING IS 'Si se encuentra en espera = ''Y'', ''N'' en caso contrario';

COMMENT ON COLUMN RAWMATERIAL_PROVIDER.RAW_MATERIAL IS 'Materia prima';

COMMENT ON COLUMN RAWMATERIAL_PROVIDER.PROVIDER IS 'Proveedor';

COMMENT ON COLUMN RAWMATERIAL_PROVIDER.UNIT_COST IS 'Costo por unidad';

COMMENT ON COLUMN RAWMATERIAL_PROVIDER.DELIVER_TIME IS 'Tiempo de entrega';

COMMENT ON COLUMN RAW_MATERIAL.UNIT IS 'Unidad de medida del material';

COMMENT ON COLUMN RAW_MATERIAL.MIN_QUANTITY IS 'Minima cantidad que se puede vender';

COMMENT ON COLUMN RAW_MATERIAL.CURRENT_EXISTENCE IS 'Existencia Actual';

COMMENT ON COLUMN RAW_MATERIAL.UNIT_COST IS 'Costo por unidad';

COMMENT ON COLUMN RAW_MATERIAL.DESCRIPTION IS 'Descripcion';

COMMENT ON COLUMN RECIPE.GARMENT IS 'Prenda';

COMMENT ON COLUMN RECIPE.STYLE IS 'Estilo';

COMMENT ON COLUMN RECIPE.GARMENT_SIZE IS 'Talla';

COMMENT ON COLUMN RECIPE_RAWMATERIAL.RECIPE IS 'Talla, prenda y estilo';

COMMENT ON COLUMN RECIPE_RAWMATERIAL.RAW_MATERIAL IS 'Materia prima necesaria';

COMMENT ON COLUMN RECIPE_RAWMATERIAL.QUANTITY IS 'Cantidad';

COMMENT ON COLUMN STYLE.COLOR IS 'Color de la prenda';

COMMENT ON COLUMN STYLE.DESCRIPTION IS 'Descripcion del estilo';
